### PR TITLE
Upgrade to 5.5.3

### PR DESCRIPTION
**Pull request by Thovi98**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Thovi98** [comment]
!testme

**Comment by OniriCorpe** [comment]
now that weblate is requiring Python 3.10 starting with 5.5, the package is stuck waiting for bookworm :/
(well unless we compile python but sighhhh)

**Comment by OniriCorpe** [comment]
!bookwormtestme

**Comment by Thovi98** [comment]
Indeed, but I see no urgent reason to to that (no security flaws discovered) so I'd rather wait :)

**Comment by kay0u** [comment]
!testme

**Review by kay0u — APPROVED** [review]
LGTM, ready to merge when you want @Thovi98

**Comment by Thovi98** [comment]
Do you think it’s recommended to merge this before official bookworm release?
The main CI will tag this as broken…

**Comment by kay0u** [comment]
We can wait the stable version of bookworm 👍

**Comment by Thovi98** [comment]
!testme

**Pull request merged**
