### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by kay0u**

### CODE REVIEW

**Comment by kay0u** [comment]
!testme

**Review by alexAubin — COMMENTED** [review]
>ImportError: cannot import name 'report_error' from 'weblate.utils.errors'

The script failed at failing :thinking: 

(but otherwise LGTM ¯\\\_(ツ)\_/¯)

**Comment by kay0u** [comment]
Yeah, I don't like this error, but I can't reproduce on my side..
To merge or not to merge, that's the question

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Pull request merged**
