### PR TITLE
[Buster] Fix python3.5 not existing

### PR DESCRIPTION
**Pull request by maniackcrudelis**
It fails later with `ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/var/www/weblate/venv/lib/python3.7/site-packages/django/utils/encoding.py)`

### CODE REVIEW

**Comment by Jibec** [comment]
I have decided to use another way of doing it. thank you anyway

**Comment by maniackcrudelis** [comment]
> I have decided to use another way of doing it. thank you anyway

Nice to hear, a PR to fix the support for Buster would be welcome though...
And also explanation about the "other way"...

We're trying to fix apps for Buster

**Comment by Jibec** [comment]
it's in master already

**Comment by maniackcrudelis** [comment]
Ok... But maybe you didn't read that PR before just closing it...
First, I did get the actual content of the directory to not have to rely to an if that will fail again as soon as it won't be python3.7

And then, I explained it was not enough...
So we still need a fucking fix for Buster !!!

**Comment by maniackcrudelis** [comment]
So... I reopen that PR, so we can fix the current bug on Buster.
The bug, fixed by the PR, can stay as it is now on master. However to have a more resilient fix seems better...

If you have any idea about the bug with `python_2_unicode_compatible`, please commit here so we can have a proper PR for that matter.

Also, DO NOT CLOSE AND DELETE again that PR... I won't give you any more warning about that...

**Comment by Jibec** [comment]
I maintain Weblate, Kresus and Funkwhale applications.
Kresus is slowly moving to nicofrand.
Funkwhale can go with you if you wish to maintain it.
Weblate stays under my responsibility.

Please stop your actions on these applications.
What you with good technical reasons it is just harassment, because you don't like me.

So what if these apps are not compatible with buster? None of your business. You are not the maintainer.
So what if I solved the issue with my own way of doing it? None of your business. You are not the maintainer.

Please do not respond or threaten me anymore.

**Comment by maniackcrudelis** [comment]
... And yet I tried to be nice...

We're actually working on Buster support for all apps that are currently level 7.
For some of them, the maintainer is already working on it, so we don't have anything to do. For others no fix is on its way.
So we're working on many different apps to push fixes for Buster.

This app has an issue opened since 26 days, and no fix. So, I come investigate the issue.

Even though I don't like you. That's right... This is not harassment, this is just shared work on a common problem for our users. And your app (as it starts by a 'w') is the last one on a long list of app we've already worked on.
It may not look obvious, but I'm actually here to help you with this package.
When the app has a maintainer, like this one, we usually just make a PR, and submit it to approval by the maintainer.
You are the maintainer of this app, which doesn't mean this app belongs to you. This app belongs to the community, which is, considering the app is level 7, expecting the app to work.

As a member of the apps group, this is actually my business to be sure this app does work on Buster, and to be sure it will work after Buster with a resilient fix.

Considering you've closed that PR twice... Acting like a child who doesn't want to share his toy... I confiscate your write permission on this repo for the time of this fix...
If you act like a child... I treat you like a child... And that's a pity...

PS: Meanwhile, if you have any idea about what is the error, a fix is still welcome.

**Comment by Jibec** [comment]
Well, there is where we disagree: the ownership.

The fact there is an apps group or people with more skills doesn't mean its members can come and change whatever they want or are more power because they are a member of a specific group.
And if they have, there should be clear guidelines on when this group can bypass the package maintainer.
The only thing our organization defines for Apps group responsibility is the ownership of official apps: https://github.com/YunoHost/project-organization/

Taking time to solve issues should not be a problem.
The fact that you opened your PR while my CI was running on my slow laptop is just no luck.
The buster branch you created only contains a fix for something that is already fixed in master. Or does the buster branch have other usage I don't know about?

If some apps may lower user experience because of a lack of buster support, then YunoHost should prevent the user to upgrade. You have the data for it.

Maybe it's time not being maintainer anymore and come back as a user: https://github.com/YunoHost/apps/pull/920
I'm sure it will be better like this.
Farewell, and thank you for all your work.

**Comment by maniackcrudelis** [comment]
The problem here is not that you're taking too long to fix anything.
The problem here is your behavior regarding contributions on this repo.

You didn't fix the support for Buster, neither you did answer to the issue opened by Alex. So I opened a pull request.
You closed it and deleted the branch without much of an explanation. But the issue is not solved...

It appears that yes I could have pushed my fix on master and didn't ask for everything, and yet I didn't... I opened a pull request, open to further contributions and this matter.

The fact is that you're not alone working on this app. Apps belong to our community, not just you.
And the fact that you're not alone is also why you can take more time to fix something. If someone else is bothered, that other person may likely open a pull request to fix the problem for others.

If it has to be said clearly, **everyone** is free to contribute to any apps package in YunoHost.

**Comment by maniackcrudelis** [comment]
So, it appears that the error `ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/var/www/weblate/venv/lib/python3.7/site-packages/django/utils/encoding.py)` is because of recent  version of Django that has dropped support for `python_2_unicode_compatible` which is an old python2 lib.

To restrict Django to version 2 (currently 2.2.12) fix that issue.

And then, I got a 502 because nginx can't open the socket.
That was solved by forcing uwsgi to use the gid www-data, so it create the socket with the correct permission for nginx.

Still to be tested.
(And first, to modify correctly the systemd config file would be better...)

**Comment by maniackcrudelis** [comment]
Still an error, if celery start after weblate, the permission are not respected on the socket.
To be investigated...

**Comment by kay0u** [comment]
I can't install this app with my 3.8/40 ynh-dev
Here logs from the 3.8:
https://paste.yunohost.org/gakukacono

**Comment by maniackcrudelis** [comment]
No problem to install on 3.8, just now.
In your log, it seems that no dependencies can be installed. Sure your VM is not broken ?

**Comment by kay0u** [comment]
I tried without any problem to install htop.

If I apt install dependenci

**Comment by maniackcrudelis** [comment]
`libglib2.0-dev` is available both on stretch and buster https://packages.debian.org/search?keywords=libglib2.0-dev&searchon=names&suite=all&section=all and depends indeed on libpcre3-dev (>= 1:8.31)
But, `libpcre3-dev` is at the version 2:8.39-3 on stretch, https://packages.debian.org/stretch/libpcre3-dev

So, for me it should work.

**Comment by maniackcrudelis** [comment]
Finally found and fix the support Buster (without breaking Stretch)

That's actually celery that does set the permission on the socket.
To change the permission only in this service is enough to have the correct permission.

I don't know why on Buster the permissions are not set correctly, while on Stretch the permission is already on www-data for the group.

I found another problem, which is not related to Stretch, Buster or this branch.
If we restart one of the 2 services of weblate, the other one will lose its socket or pid files.
You can only stop both services, then start both again. But not directly restart any of them.

Anyway, this branch now works both on Buster and Stretch :tada: 

@Jibec, your review on these changes are highly welcome :+1: 
Otherwise we'll merge anyway...

**Comment by kay0u** [comment]
Yet another problem with sury:

To reproduce my issue:
- Install snipeit (buster branch with sury), I guess you can install nextcloud too.
- Remove it
- Install weblate.

After that weblate can't install anymore, I have the problem above. If I try to install the dependencies manually, I get this error:

> libpcre3-dev : Depends: libpcre3 (= 2:8.39-3) but 2:8.43-1+0~20190710.6+debian9~1.gbpbfc49f is to be installed

**Comment by maniackcrudelis** [comment]
Sury always sury...
I'll have a look to it

**Pull request merged**
