### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by kay0u**
## Solution

- *4.11*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by kay0u** [comment]
!testme

**Comment by alexAubin** [comment]
```
111821 WARNING Traceback (most recent call last):
111822 WARNING   File "/usr/bin/virtualenv", line 11, in <module>
111823 WARNING     load_entry_point('virtualenv==15.1.0', 'console_scripts', 'virtualenv')()
111823 WARNING   File "/usr/lib/python3/dist-packages/virtualenv.py", line 724, in main
111823 WARNING     symlink=options.symlink)
111824 WARNING   File "/usr/lib/python3/dist-packages/virtualenv.py", line 996, in create_environment
111824 WARNING     download=download,
111825 WARNING   File "/usr/lib/python3/dist-packages/virtualenv.py", line 926, in install_wheel
111825 WARNING     call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
111826 WARNING   File "/usr/lib/python3/dist-packages/virtualenv.py", line 817, in call_subprocess
111826 WARNING     % (cmd_desc, proc.returncode))
111827 WARNING OSError: Command /var/www/weblate/venv/bin/python3 - setuptools pkg_resources pip wheel failed with error code 2
112417 WARNING [Error] Upgrade failed.
286472 WARNING 110725 ERROR:  must be owner of extension pg_trgm
```

Uuuugh, that's weird ? That message about 'must be owner of extension pg_trgm' seems to point to a permission issue, but I'm not sure that's the actual error message ? Something's going on with setuptools / pip / wheel

**Comment by alexAubin** [comment]
Before this there's also

```
326947 INFO DEBUG -   File "/var/www/weblate/venv/share/python-wheels/packaging-19.0-py2.py3-none-any.whl/packaging/version.py", line 219, in __init__
326947 INFO DEBUG -     match = self._regex.search(version)
326947 INFO DEBUG - TypeError: expected string or bytes-like object
```

Where it seems to be miserably crashing about parsing a version

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
(╯°□°)╯︵ ┻━┻

**Comment by yalh76** [comment]
> (╯°□°)╯︵ ┻━┻

the issue comes from https://github.com/YunoHost-Apps/weblate_ynh/blob/f3dec1623b80e9342f5483b553fdd9b2fd17b077/scripts/upgrade#L162

or you don't recreate an existing venv or you remove it befroe creating it ^^

**Comment by yalh76** [comment]
!testme

**Pull request merged**
