### PR TITLE
4.13.1

### LINKED ISSUE #58: buster failed install
### Describe the bug

*Weblate no more install on buster.*

### CI logs:
https://ci-apps.yunohost.org/ci/logs/weblate_amd64_stable_complete.log or https://ci-apps.yunohost.org/ci/job/8554
`#  include "xxhash.c"   /* include xxhash function bodies as `static`, for inlining */`

Seems that the issue comes from borgbackup, that requires `libxxhash >= 0.8.1` https://borgbackup.readthedocs.io/en/stable/installation.html#pyinstaller-binary

Installation goes fine when building xxhash from source: https://github.com/Cyan4973/xxHash

so two options:

1. make the package requires bullseye
2. build xxhash from sources

what we do ?

### PR DESCRIPTION
**Pull request by kay0u**
## Problem

- *Fix #58*

## Solution

- *Apply example_ynh*
- *Upgrade to 4.13.1*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by kay0u** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!bullseyetestme

**Comment by yalh76** [comment]
@kay0u : weblate seems fixed ^^

**Comment by kay0u** [comment]
!testme

**Pull request merged**
