### PR TITLE
Upgrade to 2.20

### PR DESCRIPTION
**Pull request by Jibec**
This upgrade took me a lot of time for multiple reasons:
* the uwsgi service is now generic and really fast (stopping service was > 1 minute, it is now < 1 second)
* the full migration to python 3.4, finally undone because of an openid bug...
* two version updates

@ozbek, @BoFFire, @mrPsycho: if one of you can try this (don't try production yet!), I would greatly appreciate!

### CODE REVIEW

**Comment by ozbek** [comment]
Upgraded using command `yunohost app upgrade -u https://github.com/YunoHost-Apps/weblate_ynh/tree/testing weblate` and it is broken :/

On web interface I am seeing 
```
Django Version: 1.11.8
Exception Type: AttributeError
Exception Value: 'WSGIRequest' object has no attribute 'user'
Exception Location: /var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/trans/views/basic.py in home, line 181
Python Executable: /usr/bin/uwsgi-core
Python Version: 2.7.9
```
Before upgrade `yunohost service status` was showing 
```
weblate: 
  loaded: not-found
  status: running
```
Afterwards it became
```
uwsgi-app@weblate.socket: 
  loaded: not-found
  status: inactive
```

**Comment by Jibec** [comment]
Well well well, what can this be related to...
Can you please provide more information? What's the configuration and what does the uwsgi says?
So you have a user "weblate"?
Thank you for the testing!

**Comment by ozbek** [comment]
Yes, there is a user `weblate`.

```
# su weblate 
weblate@YunoHost:/root$ whoami
weblate
```


```
# cat /var/log/uwsgi/app/weblate 
*** Starting uWSGI 2.0.7-debian (32bit) on [Wed Apr 11 23:24:02 2018] ***
compiled with version: 4.9.2 on 17 March 2018 22:33:35
os: Linux-4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017
nodename: YunoHost
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /
detected binary path: /usr/bin/uwsgi-core
your processes number limit is 7314
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
- SystemD socket activation detected -
uwsgi socket 2 attached to UNIX address /var/run/uwsgi/weblate.socket fd 3
Python version: 2.7.9 (default, Sep 17 2016, 20:55:23)  [GCC 4.9.2]
Set PythonHome to /var/www/weblate/venv
Python main interpreter initialized at 0xf58958
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 136704 bytes (133 KB) for 1 cores
*** Operational MODE: single process ***
mounting /var/www/weblate/venv/lib/python2.7/site-packages/weblate/wsgi.py on /weblate
WSGI app 0 (mountpoint='/weblate') ready in 5 seconds on interpreter 0xf58958 pid: 315 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 315)
spawned uWSGI worker 1 (pid: 333, cores: 1)
[pid: 333|app: 0|req: 1/1] xxx.xxx.xx.xxx () {46 vars in 844 bytes} [Wed Apr 11 23:24:07 2018] GET /weblate/ => generated 4388 bytes in 4186 msecs (HTTP/1.1 500) 5 headers in 182 bytes (1 switches on core 0)
[pid: 333|app: 0|req: 2/2] xxx.xxx.xx.xxx () {44 vars in 743 bytes} [Wed Apr 11 23:24:11 2018] GET /weblate/js/i18n/ => generated 3217 bytes in 180 msecs (HTTP/1.1 200) 5 headers in 154 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.7-debian (32bit) on [Wed Apr 11 23:37:13 2018] ***
compiled with version: 4.9.2 on 17 March 2018 22:33:35
os: Linux-4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017
nodename: YunoHost
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /
detected binary path: /usr/bin/uwsgi-core
your processes number limit is 7314
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
- SystemD socket activation detected -
uwsgi socket 2 attached to UNIX address /var/run/uwsgi/weblate.socket fd 3
Python version: 2.7.9 (default, Sep 17 2016, 20:55:23)  [GCC 4.9.2]
Set PythonHome to /var/www/weblate/venv
Python main interpreter initialized at 0x612958
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 136704 bytes (133 KB) for 1 cores
*** Operational MODE: single process ***
mounting /var/www/weblate/venv/lib/python2.7/site-packages/weblate/wsgi.py on /weblate
WSGI app 0 (mountpoint='/weblate') ready in 9 seconds on interpreter 0x612958 pid: 2059 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2059)
spawned uWSGI worker 1 (pid: 2091, cores: 1)
ERROR Internal Server Error: /weblate/
Traceback (most recent call last):
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/trans/views/basic.py", line 181, in home
    user = request.user
AttributeError: 'WSGIRequest' object has no attribute 'user'
Internal Server Error: /weblate/
Traceback (most recent call last):
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/trans/views/basic.py", line 181, in home
    user = request.user
AttributeError: 'WSGIRequest' object has no attribute 'user'
[pid: 2091|app: 0|req: 1/1] xxx.xxx.xx.xxx () {56 vars in 1267 bytes} [Wed Apr 11 23:37:22 2018] GET /weblate => generated 99707 bytes in 1768 msecs (HTTP/1.1 500) 5 headers in 168 bytes (1 switches on core 0)
```

**Comment by Jibec** [comment]
OK, arm again... Is it a Raspberry?

**Comment by ozbek** [comment]
Yes, Raspberry Pi 3.

**Comment by ozbek** [comment]
Just tried another clean upgrade from 2.17.1 and the upgrade failed again (aside from someone had tried to ssh with user pi, I have no clue why it failed):

```
# yunohost app upgrade -u https://github.com/YunoHost-Apps/weblate_ynh/tree/testing weblate
Warning: Upgrading app weblate...
Warning: Removed symlink /etc/systemd/system/multi-user.target.wants/weblate.service.
Warning: Avoid deleting /var/www/weblate/bin/.
Warning: perl: warning: Setting locale failed.
Warning: perl: warning: Please check that your locale settings:
Warning:    LANGUAGE = (unset),
Warning:    LC_ALL = (unset),
Warning:    LC_PAPER = "en_US.UTF-8",
Warning:    LC_ADDRESS = "en_US.UTF-8",
Warning:    LC_MONETARY = "en_US.UTF-8",
Warning:    LC_NUMERIC = "en_US.UTF-8",
Warning:    LC_TELEPHONE = "en_US.UTF-8",
Warning:    LC_IDENTIFICATION = "en_US.UTF-8",
Warning:    LC_MEASUREMENT = "en_US.UTF-8",
Warning:    LC_TIME = "en_US.UTF-8",
Warning:    LC_NAME = "en_US.UTF-8",
Warning:    LANG = "en_GB.UTF-8"
Warning:     are supported and installed on your system.
Warning: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Warning: perl: warning: Setting locale failed.
Warning: perl: warning: Please check that your locale settings:
Warning:    LANGUAGE = (unset),
Warning:    LC_ALL = (unset),
Warning:    LC_NAME = "en_US.UTF-8",
Warning:    LC_NUMERIC = "en_US.UTF-8",
Warning:    LC_TIME = "en_US.UTF-8",
Warning:    LC_MONETARY = "en_US.UTF-8",
Warning:    LC_TELEPHONE = "en_US.UTF-8",
Warning:    LC_PAPER = "en_US.UTF-8",
Warning:    LC_MEASUREMENT = "en_US.UTF-8",
Warning:    LC_IDENTIFICATION = "en_US.UTF-8",
Warning:    LC_ADDRESS = "en_US.UTF-8",
Warning:    LANG = "en_GB.UTF-8"
Warning:     are supported and installed on your system.
Warning: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Warning: perl: warning: Setting locale failed.
Warning: perl: warning: Please check that your locale settings:
Warning:    LANGUAGE = (unset),
Warning:    LC_ALL = (unset),
Warning:    LC_NAME = "en_US.UTF-8",
Warning:    LC_NUMERIC = "en_US.UTF-8",
Warning:    LC_TIME = "en_US.UTF-8",
Warning:    LC_MONETARY = "en_US.UTF-8",
Warning:    LC_TELEPHONE = "en_US.UTF-8",
Warning:    LC_PAPER = "en_US.UTF-8",
Warning:    LC_MEASUREMENT = "en_US.UTF-8",
Warning:    LC_IDENTIFICATION = "en_US.UTF-8",
Warning:    LC_ADDRESS = "en_US.UTF-8",
Warning:    LANG = "en_GB.UTF-8"
Warning:     are supported and installed on your system.
Warning: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Warning: perl: warning: Setting locale failed.
Warning: perl: warning: Please check that your locale settings:
Warning:    LANGUAGE = (unset),
Warning:    LC_ALL = (unset),
Warning:    LC_NAME = "en_US.UTF-8",
Warning:    LC_NUMERIC = "en_US.UTF-8",
Warning:    LC_TIME = "en_US.UTF-8",
Warning:    LC_MONETARY = "en_US.UTF-8",
Warning:    LC_TELEPHONE = "en_US.UTF-8",
Warning:    LC_PAPER = "en_US.UTF-8",
Warning:    LC_MEASUREMENT = "en_US.UTF-8",
Warning:    LC_IDENTIFICATION = "en_US.UTF-8",
Warning:    LC_ADDRESS = "en_US.UTF-8",
Warning:    LANG = "en_GB.UTF-8"
Warning:     are supported and installed on your system.
Warning: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Warning: perl: warning: Setting locale failed.
Warning: perl: warning: Please check that your locale settings:
Warning:    LANGUAGE = (unset),
Warning:    LC_ALL = (unset),
Warning:    LC_NAME = "en_US.UTF-8",
Warning:    LC_NUMERIC = "en_US.UTF-8",
Warning:    LC_TIME = "en_US.UTF-8",
Warning:    LC_MONETARY = "en_US.UTF-8",
Warning:    LC_TELEPHONE = "en_US.UTF-8",
Warning:    LC_PAPER = "en_US.UTF-8",
Warning:    LC_MEASUREMENT = "en_US.UTF-8",
Warning:    LC_IDENTIFICATION = "en_US.UTF-8",
Warning:    LC_ADDRESS = "en_US.UTF-8",
Warning:    LANG = "en_GB.UTF-8"
Warning:     are supported and installed on your system.
Warning: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Warning: perl: warning: Setting locale failed.
Warning: perl: warning: Please check that your locale settings:
Warning:    LANGUAGE = (unset),
Warning:    LC_ALL = (unset),
Warning:    LC_NAME = "en_US.UTF-8",
Warning:    LC_NUMERIC = "en_US.UTF-8",
Warning:    LC_TIME = "en_US.UTF-8",
Warning:    LC_MONETARY = "en_US.UTF-8",
Warning:    LC_TELEPHONE = "en_US.UTF-8",
Warning:    LC_PAPER = "en_US.UTF-8",
Warning:    LC_MEASUREMENT = "en_US.UTF-8",
Warning:    LC_IDENTIFICATION = "en_US.UTF-8",
Warning:    LC_ADDRESS = "en_US.UTF-8",
Warning:    LANG = "en_GB.UTF-8"
Warning:     are supported and installed on your system.
Warning: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Warning: perl: warning: Setting locale failed.
Warning: perl: warning: Please check that your locale settings:
Warning:    LANGUAGE = (unset),
Warning:    LC_ALL = (unset),
Warning:    LC_NAME = "en_US.UTF-8",
Warning:    LC_NUMERIC = "en_US.UTF-8",
Warning:    LC_TIME = "en_US.UTF-8",
Warning:    LC_MONETARY = "en_US.UTF-8",
Warning:    LC_TELEPHONE = "en_US.UTF-8",
Warning:    LC_PAPER = "en_US.UTF-8",
Warning:    LC_MEASUREMENT = "en_US.UTF-8",
Warning:    LC_IDENTIFICATION = "en_US.UTF-8",
Warning:    LC_ADDRESS = "en_US.UTF-8",
Warning:    LANG = "en_GB.UTF-8"
Warning:     are supported and installed on your system.
Warning: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Warning: dh_install: Compatibility levels before 9 are deprecated (level 7 in use)
Warning: perl: warning: Setting locale failed.
Warning: perl: warning: Please check that your locale settings:
Warning:    LANGUAGE = (unset),
Warning:    LC_ALL = (unset),
Warning:    LC_NAME = "en_US.UTF-8",
Warning:    LC_NUMERIC = "en_US.UTF-8",
Warning:    LC_TIME = "en_US.UTF-8",
Warning:    LC_MONETARY = "en_US.UTF-8",
Warning:    LC_TELEPHONE = "en_US.UTF-8",
Warning:    LC_PAPER = "en_US.UTF-8",
Warning:    LC_MEASUREMENT = "en_US.UTF-8",
Warning:    LC_IDENTIFICATION = "en_US.UTF-8",
Warning:    LC_ADDRESS = "en_US.UTF-8",
Warning:    LANG = "en_GB.UTF-8"
Warning:     are supported and installed on your system.
Warning: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Warning: dh_installdocs: Compatibility levels before 9 are deprecated (level 7 in use)
Warning: perl: warning: Setting locale failed.
Warning: perl: warning: Please check that your locale settings:
Warning:    LANGUAGE = (unset),
Warning:    LC_ALL = (unset),
Warning:    LC_NAME = "en_US.UTF-8",
Warning:    LC_NUMERIC = "en_US.UTF-8",
Warning:    LC_TIME = "en_US.UTF-8",
Warning:    LC_MONETARY = "en_US.UTF-8",
Warning:    LC_TELEPHONE = "en_US.UTF-8",
Warning:    LC_PAPER = "en_US.UTF-8",
Warning:    LC_MEASUREMENT = "en_US.UTF-8",
Warning:    LC_IDENTIFICATION = "en_US.UTF-8",
Warning:    LC_ADDRESS = "en_US.UTF-8",
Warning:    LANG = "en_GB.UTF-8"
Warning:     are supported and installed on your system.
Warning: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Warning: perl: warning: Setting locale failed.
Warning: perl: warning: Please check that your locale settings:
Warning:    LANGUAGE = (unset),
Warning:    LC_ALL = (unset),
Warning:    LC_NAME = "en_US.UTF-8",
Warning:    LC_NUMERIC = "en_US.UTF-8",
Warning:    LC_TIME = "en_US.UTF-8",
Warning:    LC_MONETARY = "en_US.UTF-8",
Warning:    LC_TELEPHONE = "en_US.UTF-8",
Warning:    LC_PAPER = "en_US.UTF-8",
Warning:    LC_MEASUREMENT = "en_US.UTF-8",
Warning:    LC_IDENTIFICATION = "en_US.UTF-8",
Warning:    LC_ADDRESS = "en_US.UTF-8",
Warning:    LANG = "en_GB.UTF-8"
Warning:     are supported and installed on your system.
Warning: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Warning: perl: warning: Setting locale failed.
Warning: perl: warning: Please check that your locale settings:
Warning:    LANGUAGE = (unset),
Warning:    LC_ALL = (unset),
Warning:    LC_NAME = "en_US.UTF-8",
Warning:    LC_NUMERIC = "en_US.UTF-8",
Warning:    LC_TIME = "en_US.UTF-8",
Warning:    LC_MONETARY = "en_US.UTF-8",
Warning:    LC_TELEPHONE = "en_US.UTF-8",
Warning:    LC_PAPER = "en_US.UTF-8",
Warning:    LC_MEASUREMENT = "en_US.UTF-8",
Warning:    LC_IDENTIFICATION = "en_US.UTF-8",
Warning:    LC_ADDRESS = "en_US.UTF-8",
Warning:    LANG = "en_GB.UTF-8"
Warning:     are supported and installed on your system.
Warning: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Warning: dh_installchangelogs: Compatibility levels before 9 are deprecated (level 7 in use)
Warning: perl: warning: Setting locale failed.
Warning: perl: warning: Please check that your locale settings:
Warning:    LANGUAGE = (unset),
Warning:    LC_ALL = (unset),
Warning:    LC_NAME = "en_US.UTF-8",
Warning:    LC_NUMERIC = "en_US.UTF-8",
Warning:    LC_TIME = "en_US.UTF-8",
Warning:    LC_MONETARY = "en_US.UTF-8",
Warning:    LC_TELEPHONE = "en_US.UTF-8",
Warning:    LC_PAPER = "en_US.UTF-8",
Warning:    LC_MEASUREMENT = "en_US.UTF-8",
Warning:    LC_IDENTIFICATION = "en_US.UTF-8",
Warning:    LC_ADDRESS = "en_US.UTF-8",
Warning:    LANG = "en_GB.UTF-8"
Warning:     are supported and installed on your system.
Warning: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Warning: perl: warning: Setting locale failed.
Warning: perl: warning: Please check that your locale settings:
Warning:    LANGUAGE = (unset),
Warning:    LC_ALL = (unset),
Warning:    LC_NAME = "en_US.UTF-8",
Warning:    LC_NUMERIC = "en_US.UTF-8",
Warning:    LC_TIME = "en_US.UTF-8",
Warning:    LC_MONETARY = "en_US.UTF-8",
Warning:    LC_TELEPHONE = "en_US.UTF-8",
Warning:    LC_PAPER = "en_US.UTF-8",
Warning:    LC_MEASUREMENT = "en_US.UTF-8",
Warning:    LC_IDENTIFICATION = "en_US.UTF-8",
Warning:    LC_ADDRESS = "en_US.UTF-8",
Warning:    LANG = "en_GB.UTF-8"
Warning:     are supported and installed on your system.
Warning: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Warning: perl: warning: Setting locale failed.
Warning: perl: warning: Please check that your locale settings:
Warning:    LANGUAGE = (unset),
Warning:    LC_ALL = (unset),
Warning:    LC_NAME = "en_US.UTF-8",
Warning:    LC_NUMERIC = "en_US.UTF-8",
Warning:    LC_TIME = "en_US.UTF-8",
Warning:    LC_MONETARY = "en_US.UTF-8",
Warning:    LC_TELEPHONE = "en_US.UTF-8",
Warning:    LC_PAPER = "en_US.UTF-8",
Warning:    LC_MEASUREMENT = "en_US.UTF-8",
Warning:    LC_IDENTIFICATION = "en_US.UTF-8",
Warning:    LC_ADDRESS = "en_US.UTF-8",
Warning:    LANG = "en_GB.UTF-8"
Warning:     are supported and installed on your system.
Warning: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Warning: dh_installdeb: Compatibility levels before 9 are deprecated (level 7 in use)
Warning: perl: warning: Setting locale failed.
Warning: perl: warning: Please check that your locale settings:
Warning:    LANGUAGE = (unset),
Warning:    LC_ALL = (unset),
Warning:    LC_NAME = "en_US.UTF-8",
Warning:    LC_NUMERIC = "en_US.UTF-8",
Warning:    LC_TIME = "en_US.UTF-8",
Warning:    LC_MONETARY = "en_US.UTF-8",
Warning:    LC_TELEPHONE = "en_US.UTF-8",
Warning:    LC_PAPER = "en_US.UTF-8",
Warning:    LC_MEASUREMENT = "en_US.UTF-8",
Warning:    LC_IDENTIFICATION = "en_US.UTF-8",
Warning:    LC_ADDRESS = "en_US.UTF-8",
Warning:    LANG = "en_GB.UTF-8"
Warning:     are supported and installed on your system.
Warning: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Warning: perl: warning: Setting locale failed.
Warning: perl: warning: Please check that your locale settings:
Warning:    LANGUAGE = (unset),
Warning:    LC_ALL = (unset),
Warning:    LC_NAME = "en_US.UTF-8",
Warning:    LC_NUMERIC = "en_US.UTF-8",
Warning:    LC_TIME = "en_US.UTF-8",
Warning:    LC_MONETARY = "en_US.UTF-8",
Warning:    LC_TELEPHONE = "en_US.UTF-8",
Warning:    LC_PAPER = "en_US.UTF-8",
Warning:    LC_MEASUREMENT = "en_US.UTF-8",
Warning:    LC_IDENTIFICATION = "en_US.UTF-8",
Warning:    LC_ADDRESS = "en_US.UTF-8",
Warning:    LANG = "en_GB.UTF-8"
Warning:     are supported and installed on your system.
Warning: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Warning: perl: warning: Setting locale failed.
Warning: perl: warning: Please check that your locale settings:
Warning:    LANGUAGE = (unset),
Warning:    LC_ALL = (unset),
Warning:    LC_NAME = "en_US.UTF-8",
Warning:    LC_NUMERIC = "en_US.UTF-8",
Warning:    LC_TIME = "en_US.UTF-8",
Warning:    LC_MONETARY = "en_US.UTF-8",
Warning:    LC_TELEPHONE = "en_US.UTF-8",
Warning:    LC_PAPER = "en_US.UTF-8",
Warning:    LC_MEASUREMENT = "en_US.UTF-8",
Warning:    LC_IDENTIFICATION = "en_US.UTF-8",
Warning:    LC_ADDRESS = "en_US.UTF-8",
Warning:    LANG = "en_GB.UTF-8"
Warning:     are supported and installed on your system.
Warning: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Warning: perl: warning: Setting locale failed.
Warning: perl: warning: Please check that your locale settings:
Warning:    LANGUAGE = (unset),
Warning:    LC_ALL = (unset),
Warning:    LC_NAME = "en_US.UTF-8",
Warning:    LC_NUMERIC = "en_US.UTF-8",
Warning:    LC_TIME = "en_US.UTF-8",
Warning:    LC_MONETARY = "en_US.UTF-8",
Warning:    LC_TELEPHONE = "en_US.UTF-8",
Warning:    LC_PAPER = "en_US.UTF-8",
Warning:    LC_MEASUREMENT = "en_US.UTF-8",
Warning:    LC_IDENTIFICATION = "en_US.UTF-8",
Warning:    LC_ADDRESS = "en_US.UTF-8",
Warning:    LANG = "en_GB.UTF-8"
Warning:     are supported and installed on your system.
Warning: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Warning: perl: warning: Setting locale failed.
Warning: perl: warning: Please check that your locale settings:
Warning:    LANGUAGE = (unset),
Warning:    LC_ALL = (unset),
Warning:    LC_NAME = "en_US.UTF-8",
Warning:    LC_NUMERIC = "en_US.UTF-8",
Warning:    LC_TIME = "en_US.UTF-8",
Warning:    LC_MONETARY = "en_US.UTF-8",
Warning:    LC_TELEPHONE = "en_US.UTF-8",
Warning:    LC_PAPER = "en_US.UTF-8",
Warning:    LC_MEASUREMENT = "en_US.UTF-8",
Warning:    LC_IDENTIFICATION = "en_US.UTF-8",
Warning:    LC_ADDRESS = "en_US.UTF-8",
Warning:    LANG = "en_GB.UTF-8"
Warning:     are supported and installed on your system.
Warning: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
Warning: Created symlink from /etc/systemd/system/sockets.target.wants/uwsgi-app@weblate.socket to /etc/systemd/system/uwsgi-app@.socket.
Warning: Job for uwsgi-app@weblate.socket failed. See 'systemctl status uwsgi-app@weblate.socket' and 'journalctl -xn' for details.
Warning: !!
Warning:   weblate's script has encountered an error. Its execution was cancelled.
Warning: !!
Warning: 
Error: Unable to upgrade weblate
Error: No app to upgrade

# systemctl status uwsgi-app@weblate.socket
● uwsgi-app@weblate.socket - Socket for uWSGI app weblate
   Loaded: loaded (/etc/systemd/system/uwsgi-app@.socket; enabled)
   Active: inactive (dead)
   Listen: /var/run/uwsgi/weblate.socket (Stream)

Apr 12 05:43:49 YunoHost systemd[1]: Starting Socket for uWSGI app weblate.
Apr 12 05:43:49 YunoHost systemd[1]: Listening on Socket for uWSGI app weblate.
Apr 16 11:37:30 YunoHost systemd[1]: Stopping Socket for uWSGI app weblate.
Apr 16 11:37:30 YunoHost systemd[1]: Closed Socket for uWSGI app weblate.
Apr 16 13:05:22 YunoHost systemd[1]: Starting Socket for uWSGI app weblate.
Apr 16 13:05:22 YunoHost systemd[1]: Socket service uwsgi-app@weblate.service already active, refusing.
Apr 16 13:05:22 YunoHost systemd[1]: Failed to listen on Socket for uWSGI app weblate.

# journalctl -xn
-- Logs begin at Thu 2018-04-12 05:43:47 UTC, end at Mon 2018-04-16 13:06:57 UTC. --
Apr 16 13:06:55 YunoHost sshd[29672]: Invalid user pi from 151.63.194.82
Apr 16 13:06:55 YunoHost sshd[29672]: input_userauth_request: invalid user pi [preauth]
Apr 16 13:06:55 YunoHost sshd[29670]: pam_unix(sshd:auth): check pass; user unknown
Apr 16 13:06:55 YunoHost sshd[29670]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=151.63.194.8
Apr 16 13:06:55 YunoHost sshd[29672]: pam_unix(sshd:auth): check pass; user unknown
Apr 16 13:06:55 YunoHost sshd[29672]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=151.63.194.8
Apr 16 13:06:57 YunoHost sshd[29670]: Failed password for invalid user pi from 151.63.194.82 port 51906 ssh2
Apr 16 13:06:57 YunoHost sshd[29672]: Failed password for invalid user pi from 151.63.194.82 port 51908 ssh2
Apr 16 13:06:57 YunoHost sshd[29670]: Connection closed by 151.63.194.82 [preauth]
Apr 16 13:06:57 YunoHost sshd[29672]: Connection closed by 151.63.194.82 [preauth]
lines 1-11/11 (END)
```

**Comment by Jibec** [comment]
Thanks for this new test, but I haven't finished the work on Raspberry 
pi.
Your error looks specific to your "locale" settings. I assume you 
changed some settings on Raspberry.

Share the full log result would be better, it is in 
/var/log/yunohost/yunohost-cli.log (if you used shell) or 
yunohost-api.log (if you used web interface).
Note this log includes passwords and other sensible information, use 
dummy passwords or clean the file before sharing it. A pastebin would be 
ok too.

**Comment by ozbek** [comment]
I tried the upgrade from command line, here is the [/var/log/yunohost/yunohost-cli.log](https://pastebin.com/2F70aBX9). As far as I can see there is not anything much though.

**Comment by Jibec** [comment]
well, I spent some time on this and have no clue what can this be related to. Is your yunohost and debian up to date ? I just re-install from scratch a new YunoHost + Weblate 2.17, then ran the upgrade, and it works fine...

**Pull request merged**
