### PR TITLE
Set DEBUG to False

### PR DESCRIPTION
**Pull request by Psycojoker**
Hello,

Setting DEBUG as True in production is a security vulnerability (as said in the documentation https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-DEBUG) and should really be avoided.

Would it be possible for you to do a release soon as it is kinda important to fix this plz? We can try to do it ourselves otherwise.

Kind regards and thanks for your work,

### CODE REVIEW

**Comment by kay0u** [comment]
Yolomerging

**Comment by Jibec** [comment]
Thank you Bram for your commit, I'll fix it out of this pull request.

@kay0u please don't merge anymore.

**Comment by kay0u** [comment]
O.o sorry if I make a mistake, but this Debug flag sounds like a security issue. And as there was no response so I merged it.

Sorry again

**Comment by Jibec** [comment]
It's fine to send a reminder, I'm not really fast to react indeed. I 
just don't like the idea someone else handle merge requests instead of 
me.

I already transmitted the maintainer role on other packages and welcome 
people who want to assume the role, but the Weblate package is important 
to me and I felt hijacked.

**Pull request merged**
