### PR TITLE
Testing

### LINKED ISSUE #60: Is there a reason github token is required?
This is a pure curiosity question: I plan to install this app on my yunohost instance, but I’m stuck at setup, due to the github token requirement. However, as all my git repository are stored elsewhere, I don’t plan to use github integration, thus this requirement sounds superfluous to me. As you can see, I do have a github account, thus I could create such token, but I’m just curious about the necessity of it.

### PR DESCRIPTION
**Pull request by kay0u**
Closes #60 

## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by kay0u** [comment]
!testme

**Comment by Thovi98** [comment]
Thanks @kay0u and @Salamandar for your help!
LGTM.

Do you think the `updater.sh` is also convertible to the new `manifest.toml` or must we disable it?

**Comment by Thovi98** [comment]
!bookwormtestme

**Comment by kay0u** [comment]
translate.yunohost.org is on 4.3.1. The upgrade crashes, and according to https://docs.weblate.org/en/latest/changes.html#weblate-5-1, we must upgrade first to 5.0.2 to be able to upgrade to 5.1+:

> Upgrades from older version than 5.0.2 are not supported, please upgrade to 5.0.2 first and then continue in upgrading.

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
FYI, i had to add some `IF EXISTS` to some migrations as explained here: https://github.com/WeblateOrg/weblate/issues/9349

**Comment by kay0u** [comment]
> Thanks @kay0u and @Salamandar for your help! LGTM.
> 
> Do you think the `updater.sh` is also convertible to the new `manifest.toml` or must we disable it?

IIRC we can remove `updater.{sh,yml}` because it's automagically handle [here](https://github.com/YunoHost-Apps/weblate_ynh/blob/3b090b15cdab5a67dfa7cf5a13f89c761c811d8e/manifest.toml#L83)

**Comment by Thovi98** [comment]
It's automagically handled for assets of the `resources.sources` but we install Weblate using pip :)

**Comment by Salamandar** [comment]
@Thovi98 some packagers use a "dummy" resource (with prefetch = false) just to be notified about updates.

**Comment by Thovi98** [comment]
> some packagers use a "dummy" resource (with prefetch = false) just to be notified about updates.

Interesting!
But I already suscribed for Weblate release notifications so it's okay I think and I suggest to disable the legacy auto updater for now.

**Comment by kay0u** [comment]
Ready to merge?

**Pull request merged**
